// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzhclMHTy0-PA0i7PJdK1Ops6Sz_MapRU',
    appId: '1:821444634282:web:f8dc31bdfa9e828ced12d3',
    messagingSenderId: '821444634282',
    projectId: 'travelapp-806ee',
    authDomain: 'travelapp-806ee.firebaseapp.com',
    storageBucket: 'travelapp-806ee.appspot.com',
    measurementId: 'G-5DQ597DKQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBljDPCl1kav62fmgqnOQtTvqxBUGmFqfk',
    appId: '1:821444634282:android:f277a1ce81c340a7ed12d3',
    messagingSenderId: '821444634282',
    projectId: 'travelapp-806ee',
    storageBucket: 'travelapp-806ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMbFiT82vdr2mr8C0vO3iF5MH-VL4gGYY',
    appId: '1:821444634282:ios:b486185f41cd6df9ed12d3',
    messagingSenderId: '821444634282',
    projectId: 'travelapp-806ee',
    storageBucket: 'travelapp-806ee.appspot.com',
    iosBundleId: 'com.example.travelgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMbFiT82vdr2mr8C0vO3iF5MH-VL4gGYY',
    appId: '1:821444634282:ios:66e180a7e1418481ed12d3',
    messagingSenderId: '821444634282',
    projectId: 'travelapp-806ee',
    storageBucket: 'travelapp-806ee.appspot.com',
    iosBundleId: 'com.example.travelgo.RunnerTests',
  );
}
